[".config/vim/autoload/plug.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod = "168h"
[".config/nvim/autoload/plug.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod = "168h"
[".config/zsh/zim/zimfw.zsh"]
  type = "file"
  url = "https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh"
